### ISSUE TITLE
MatrixSolve error when train.

### ISSUE THREAD

**Issue by liyandongpy** [tynguyen/unsupervisedDeepHomographyRAL2018#21]
![image](https://user-images.githubusercontent.com/49861986/72768414-54fb2d00-3c32-11ea-8bee-950606d880ac.png)

when i train with 1 GPU,i got this error, but i got no error when i use CPU.

**Comment by tynguyen** [comment]
Based on [this discussion](https://devtalk.nvidia.com/default/topic/1049490/container-tensorflow/-op_requires-failed-at-matrix_inverse_op-cc-191-internal-tensorflow-core-kernels-cuda_solvers-cc-803-cublas-call-failed-status-13/?offset=6#5380467), your issue might be caused by an incompatible combination of CUDA and cuDNN.
